print( "-Story Writer- ")
print()
hs = input("The title of your story: ")
cs = input("The content of your story: ")
wn = input("The writer of your story: ")
ds = input("The date of your story: ")
nw = cs.count(" ")
ss = cs.count(".")
es = cs.count("!")
qs = cs.count("?")
print()
print()
print()
print()
print("-",hs,"-")
print()
print(cs)
print()
print("writer: ",wn," "*20,"date: ",ds," "*20,"no of words: ",nw)
print("lines: ",ss+es+qs)
print()
print()
print()
print()
